export const cities = [
    "Shanghai",
    "Buenos Aires",
    "Mumbai",
    "Mexico City",
    "Karachi",
    "İstanbul",
    "Delhi",
    "Manila",
    "Moscow",
    "Dhaka",
    "Seoul",
    "São Paulo",
    "Lagos",
    "Jakarta",
    "Tokyo",
    "New York",
    "Taipei",
    "Kinshasa",
    "Lima",
    "Cairo",
    "London",
    "Beijing",
    "Tehrān",
    "Bogotá",
    "Hong Kong",
    "Rio de Janeiro",
    "Baghdad",
    "Tai’an",
    "Bangkok",
    "Bangalore",
    "Santiago",
    "Kaifeng",
    "Kolkata",
    "Toronto",
    "Sydney",
    "Wuhan",
    "Saint Petersburg",
    "Chittagong",
    "Alexandria",
    "Los Angeles",
    "Tianjin",
    "Melbourne",
    "Puyang",
    "Singapore",
    "Ankara",
    "Shenyang",
    "Hồ Chí Minh City",
    "Shiyan",
    "Cape Town",
    "Berlin",
    "Montréal",
    "Madrid",
    "Xi’an",
    "Pyongyang",
    "Casablanca",
    "Kabul",
    "Caracas",
    "Addis Ababa",
    "Nairobi",
    "Taiyuan",
    "Salvador",
    "Dar es Salaam",
    "Chicago",
    "Ōsaka-shi",
    "Mogadishu",
    "Rome",
    "Kiev",
    "Brasília",
    "Santo Domingo",
    "Paris",
    "Houston",
    "Changsh",
    "Johannesburg",
    "Algiers",
    "Beirut",
    "Bucharest",
    "Vancouver",
    "Maracay",
    "Minsk",
    "Hamburg",
    "Warsaw",
    "Budapest",
    "Vienna",
    "Rabat",
    "Guadalajara",
    "Barcelon",
    "Alepp",
    "Xinyan",
    "Puebla de Zaragoza",
    "Phnom Penh",
    "Damascus",
    "Harare",
    "Philadelphia",
    "Ciudad Juárez",
    "Kuala Lumpur",
    "Perth",
    "Phoenix",
    "Hanoi",
    "Kharkiv",
    "Stockholm", 
    "Copenhagen", 
    "Prague",
    "Dubai",
    "Mecca",
    "Sofia",
    "Dublin",
    "Brisbane",
    "San Jose",
    "Marrakech",
    "Ottawa",
    "La Paz",
    "San Francisco",
    "Kraków",
    "Riga",
    "Amsterdam",
    "Athens",
    "Jerusalem",
    "Zagreb",
    "Winnipeg "
];


